apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vprofile-app
  namespace: monitoring
  labels: { release: monitoring }
spec:
  namespaceSelector: { matchNames: [{{ .Values.namespace }}] }
  selector: { matchLabels: { app: app01 } }
  endpoints: [{ port: web, interval: 30s }]
